#!/bin/bash

# Copyright 2016, André Müller <muellan@uni-mainz.de>
#
# This file is part of the MetaCache taxonomic sequence classification tool.
#
# MetaCache is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MetaCache is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MetaCache.  If not, see <http://www.gnu.org/licenses/>.


set -u  # Protect against uninitialized vars.
set -e  # Stop on error

FTPURL="ftp://ftp.ncbi.nih.gov/genomes/ASSEMBLY_REPORTS"


function download_mapping {
  FILE=$1

  if [ ! -e "$FILE" ]; then
    echo "Downloading $FILE ... "
    wget $FTPURL/$FILE
    echo "Download complete."
  fi
}


if [ $# -lt 2 ]; then
  echo "Usage: $0 <target directory> (refseq|genbank)"
  exit
fi


TARGET=$1

mkdir -p "$TARGET"
cd "$TARGET"

echo "Downloading genome file to taxid mapping files."

if [ "$2" = "refseq" ]; then
  download_mapping assembly_summary_refseq.txt
  download_mapping assembly_summary_refseq_historical.txt
elif [ "$2" = "genbank" ]; then
  download_mapping assembly_summary_genbank.txt
  download_mapping assembly_summary_genbank_historical.txt
else
  echo "Usage: $0 <target directory> (refseq|genbank)"
  exit
fi

echo "Complete."
