#!/bin/bash

# Copyright 2016, André Müller <muellan@uni-mainz.de>
#
# This file is part of the MetaCache taxonomic sequence classification tool.
#
# MetaCache is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MetaCache is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MetaCache.  If not, see <http://www.gnu.org/licenses/>.

# This script will download complete bacterial and virus genomes from
# the NCBI RefSeq project and build a classification database.

set -u
set -e


# download-ncbi-genomes <sublibrary> <target folder>
./download-ncbi-genomes refseq/bacteria genomes 
./download-ncbi-genomes refseq/viral genomes
./download-ncbi-genomes refseq/archaea genomes

# download-ncbi-taxonomy <target folder>
./download-ncbi-taxonomy genomes/taxonomy

./metacache build refseq genomes/refseq -taxonomy genomes/taxonomy -kmerlen 16 -winlen 128 -sketchlen 16

