#!/bin/bash

# Copyright 2016, André Müller <muellan@uni-mainz.de>
#
# This file is part of the MetaCache taxonomic sequence classification tool.
#
# MetaCache is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MetaCache is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MetaCache.  If not, see <http://www.gnu.org/licenses/>.

# This script will download complete bacterial and virus genomes from
# the NCBI RefSeq project and build a classification database.

set -u  # Protect against uninitialized vars.
set -e  # Stop on error


MODE=standard

if [ $# -lt 1 ]; then
  echo "Building database for NCBI RefSeq complete bacterial and virus genomes."
  echo "Usage:    $0 (big|standard|small)"
fi


# download-ncbi-genomes <sublibrary> <target folder>
./download-ncbi-genomes refseq/bacteria genomes
./download-ncbi-genomes refseq/viral genomes
./download-ncbi-genomes refseq/archaea genomes


# download-ncbi-taxonomy <target folder>
./download-ncbi-taxonomy genomes/taxonomy
# ./download-ncbi-taxmaps  genomes/taxonomy


case "$MODE" in
"big")
    ./metacache build refseq_big genomes/refseq -taxonomy genomes/taxonomy -kmerlen 16 -winlen 127 -sketchlen 32
    ;;
"standard")
    ./metacache build refseq genomes/refseq -taxonomy genomes/taxonomy -kmerlen 16 -winlen 127 -sketchlen 16
    ;;
"small")
    ./metacache build refseq_small genomes/refseq -taxonomy genomes/taxonomy -kmerlen 16 -winlen 255 -sketchlen 16
    ;;
esac


